### ISSUE TITLE
About paper

### ISSUE THREAD

**Issue by rubyrosecraft** [micts/acgcn#1]
Thank you for your work very much. Can you share the paper link? Thank you!

**Comment by micts** [comment]
Hi @yaru-zhang. 

Thank you for your interest in our work. As mentioned in the Readme file, the paper has been submitted to _International Workshop on Deep Learning for Human Activity Understanding (DL-HAU2020)_ (in conjunction with ICPR 2020). We will provide a link to the paper shortly after the submission results are available.

I will let you know when this is the case by closing this issue.

**Comment by micts** [comment]
Paper is now available: https://liacs.leidenuniv.nl/~puttenpwhvander/library/Tsiaousis-DL-HAU2020.pdf (link is also available in project description).
